---
- hosts: all
  become: yes
  tasks:
  - name: Set swappiness if more than 2GB ram
    block:
    - sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      failed_when: ansible_memtotal_mb <= 1500
    rescue:
    - name: Print error
      debug:
        msg: "Server {{ ansible_nodename }} has less than 2048MB"
