---
- name: Install Mysql on servers
  yum: name=mysql-server state=present

- name: Allow firewall Rules
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled

- name: Reload firewalld
  shell: firewall-cmd --reload

- name: Template for Mysql DB
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: Start and Enable mysql server
  service: name=mysql state=started enabled=yes

- name: Create mysql default user
  mysql_user:
    login_user: root
    login_password: ''
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: root
    password: "{{ database_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  notify: db restart
