---
- hosts: servers
  become: yes
  gather_facts: no

  tasks:
  - name: user creation named automation
    user:
      name: automation

  - name: file creation      
    file:
      state: directory
      path: /home/automation/.ssh
      owner: automation
      mode: 0700
      group: automation

  - name: Add authorized keys using lineinfile
    lineinfile:
      path: /home/automation/.ssh/authorized_keys
      line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD2TWlcaJOkk/WridMCxxQuBmFIIxXXLoBm+AMMNnK8Rbhgwvohg4dYXvuI/t0ijtfHveJeBOCf3CKIhcBBSXBzH6oj+wmZBkZeg8m7DLeAv8sweNNZigQJKjIQoBZ3EU/DuxRcHfs1VbfpjEQddNPQw5UH+9gDLOvBk0cioX9TdMODYDrs8oEmAJGn3JulHC07dCkafpR59YI8iM1lsALsMpC3tG+wwFGF2U2yC00iiXcyIt0X7TbcYVdXqmLUb+qAyuFqjvDNYSKY1wUeKxnt9wWit+26Ck30rdNQWdxPKOTg2Q0wQZF9h+NW5TLls/h8vg4qgsg+BuzHSvm/B/a9 ansible@juanpaolosantiago4c.mylabserver.com"
      create: yes

  - name: Modify file of authorized keys
    file: 
      name: /home/automation/.ssh/authorized_keys
      mode: 0600
      owner: automation
      group: automation

  - name: Create sudoers entry for automation user for no password sudo
    lineinfile:
      path: /etc/sudoers
      line: "automation ALL=(ALL)       NOPASSWD: ALL"
      create: yes
