---
- hosts: servers
  become: yes
  vars_files:
    - /home/ansible/plays/vars/user_list.yml
    - /home/ansible/plays/secret.yml
 
 
  tasks:
  - name: user creation
    user: 
     name: jp
     password: "{{ user_password | password_hash('sha512') }}"
    when: inventory_hostname in groups.lab
 
  - debug: 
      msg:
      - '{{ user_password }}'
