---
- name: Selinux enable
  selinux:
    policy: targeted
    state: enforcing 

- name: Seboolean enable httpd can connect
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes 
